from django.urls import path

from .views import (
    AdminCategoryDetailView,
    AdminCategoryListView,
    AdminProductDetailView,
    AdminProductListCreateView,
    AdminReviewApproveView,
    AdminReviewDetailView,
    AdminReviewListView,
    AdminReviewRejectView,
    BestsellerProductsView,
    CategoryDetailView,
    CategoryListView,
    FeaturedProductsView,
    FlashSaleProductsView,
    NewArrivalProductsView,
    ProductDetailView,
    ProductListView,
    ProductReviewsView,
    ProductSearchView,
)

urlpatterns = [
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('categories/<slug:slug>/', CategoryDetailView.as_view(), name='category-detail'),
    path('', ProductListView.as_view(), name='product-list'),
    path('featured/', FeaturedProductsView.as_view(), name='featured-products'),
    path('bestsellers/', BestsellerProductsView.as_view(), name='bestseller-products'),
    path('new-arrivals/', NewArrivalProductsView.as_view(), name='new-arrival-products'),
    path('flash-sales/', FlashSaleProductsView.as_view(), name='flash-sale-products'),
    path('search/', ProductSearchView.as_view(), name='product-search'),
    path('<slug:slug>/', ProductDetailView.as_view(), name='product-detail'),
    path('<slug:slug>/reviews/', ProductReviewsView.as_view(), name='product-reviews'),
    path('admin/', AdminProductListCreateView.as_view(), name='admin-product-list'),
    path('admin/<int:pk>/', AdminProductDetailView.as_view(), name='admin-product-detail'),
    path('admin/categories/', AdminCategoryListView.as_view(), name='admin-category-list'),
    path('admin/categories/<int:pk>/', AdminCategoryDetailView.as_view(), name='admin-category-detail'),
    path('admin/reviews/', AdminReviewListView.as_view(), name='admin-review-list'),
    path('admin/reviews/<int:pk>/', AdminReviewDetailView.as_view(), name='admin-review-detail'),
    path('admin/reviews/<int:pk>/approve/', AdminReviewApproveView.as_view(), name='admin-review-approve'),
    path('admin/reviews/<int:pk>/reject/', AdminReviewRejectView.as_view(), name='admin-review-reject'),
]
