# Generated by Django 5.1.15 on 2026-06-09 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_order', 'New Order'), ('payment_received', 'Payment Received'), ('large_order', 'Large Order Alert'), ('order_cancelled', 'Order Cancelled'), ('contact_submission', 'Contact Submission'), ('low_stock', 'Low Stock'), ('daily_summary', 'Daily Summary'), ('weekly_summary', 'Weekly Summary'), ('monthly_summary', 'Monthly Summary')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
