# Generated by Django 4.2.11 on 2026-07-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_terms_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('local', 'Local (Nigeria)'), ('international', 'International')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='international_region',
            field=models.CharField(blank=True, choices=[('US', 'United States'), ('UK', 'United Kingdom'), ('CA', 'Canada')], default='', max_length=5),
        ),
    ]
