# Generated by Django 4.2.11 on 2026-06-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0002_heroimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/logos/'),
        ),
    ]
