# Generated by Django 4.2.11 on 2026-07-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0005_sitesettings_about_ceo_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngn_per_usd', models.DecimalField(decimal_places=4, default=1450, help_text='NGN per 1 USD (e.g. 1450 means $1 = ₦1,450)', max_digits=12)),
                ('ngn_per_gbp', models.DecimalField(decimal_places=4, default=1920, help_text='NGN per 1 GBP (e.g. 1920 means £1 = ₦1,920)', max_digits=12)),
                ('ngn_per_cad', models.DecimalField(decimal_places=4, default=1100, help_text='NGN per 1 CAD (e.g. 1100 means C$1 = ₦1,100)', max_digits=12)),
                ('local_delivery_fee', models.DecimalField(decimal_places=2, default=4000, help_text='Flat delivery fee for orders within Nigeria (NGN)', max_digits=10)),
                ('international_delivery_fee', models.DecimalField(decimal_places=2, default=170000, help_text='Flat delivery fee for US, UK, and Canada orders (NGN)', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store currency & FX',
                'verbose_name_plural': 'Store currency & FX',
            },
        ),
    ]
